# Generated by Django 4.2.7 on 2024-04-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
